#!/bin/bash

###########
# Script to create custom es_systems.cfg
# This is to set custom system order or hide systems from Emulation Station without having to manually edit es_systems.cfg
###########

#Set colors for status message
declare -r red='\e[1;31m'
declare -r blue='\e[1;34m'
declare -r white='\e[1;97m'
declare -r yellow='\e[1;33m'
declare -r declare -r clear='\e[0m'

ok(){
  printf "${white}[+] ${1}${clear}\n"
}

warn(){
  printf "${yellow}[-] ${1}${clear}\n"
}

die(){
  printf "${red}[-] ${1}${clear}\n"
  sleep 1
  exit 1
}

create_es_system_list(){
  local system=${1}
  case ${system} in
    ags)
      local -r name='ags'
      local -r fullname='Adventure Game Studio'
      local -r path='/home/pi/RetroPie/roms/ags'
      local -r extension='.exe .EXE'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ ags %ROM%'
      local -r platform='ags'
      local -r theme='ags'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    amstradcpc)
      local -r name='amstradcpc'
      local -r fullname='Amstrad CPC'
      local -r path='/home/pi/RetroPie/roms/amstradcpc'
      local -r extension='.cdt .cpc .dsk .zip .CDT .CPC .DSK .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ amstradcpc %ROM%'
      local -r platform='amstradcpc'
      local -r theme='amstradcpc'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    apple2)
      local -r name='apple2'
      local -r fullname='Apple II'
      local -r path='/home/pi/RetroPie/roms/apple2'
      local -r extension='.po .dsk .nib .PO .DSK .NIB'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ apple2 %ROM%'
      local -r platform='apple2'
      local -r theme='apple2'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    arcade)
      local -r name='arcade'
      local -r fullname='Arcade'
      local -r path='/home/pi/RetroPie/roms/arcade'
      local -r extension='.7z .cue .fba .iso .zip .7Z .CUE .FBA .ISO .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ arcade %ROM%'
      local -r platform='arcade'
      local -r theme='arcade'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    atari2600)
      local -r name='atari2600'
      local -r fullname='Atari 2600'
      local -r path='/home/pi/RetroPie/roms/atari2600'
      local -r extension='.7z .a26 .bin .rom .zip .gz .7Z .A26 .BIN .ROM .ZIP .GZ'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ atari2600 %ROM%'
      local -r platform='atari2600'
      local -r theme='atari2600'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    atari5200)
      local -r name='atari5200'
      local -r fullname='Atari 5200'
      local -r path='/home/pi/RetroPie/roms/atari5200'
      local -r extension='.7z .a52 .bin .car .zip .7Z .A52 .BIN .CAR .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ atari5200 %ROM%'
      local -r platform='atari5200'
      local -r theme='atari5200'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    atari7800)
      local -r name='atari7800'
      local -r fullname='Atari 7800 ProSystem'
      local -r path='/home/pi/RetroPie/roms/atari7800'
      local -r extension='.7z .a78 .bin .zip .7Z .A78 .BIN .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ atari7800 %ROM%'
      local -r platform='atari7800'
      local -r theme='atari7800'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    atari800)
      local -r name='atari800'
      local -r fullname='Atari 800'
      local -r path='/home/pi/RetroPie/roms/atari800'
      local -r extension='.7z .atr .atr.gz .atx .bas .bin .car .cas .com .dcm .rom .xex .xfd .xfd.gz .zip .7Z .ATR .ATR.GZ .ATX .BAS .BIN .CAR .CAS .COM .DCM .ROM .XEX .XFD .XFD.GZ .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ atari800 %ROM%'
      local -r platform='atari800'
      local -r theme='atari800'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    atarilynx)
      local -r name='atarilynx'
      local -r fullname='Atari Lynx'
      local -r path='/home/pi/RetroPie/roms/atarilynx'
      local -r extension='.7z .lnx .zip .7Z .LNX .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ atarilynx %ROM%'
      local -r platform='atarilynx'
      local -r theme='atarilynx'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    atarist)
      local -r name='atarist'
      local -r fullname='Atari ST'
      local -r path='/home/pi/RetroPie/roms/atarist'
      local -r extension='.st .stx .img .rom .raw .ipf .ctr .zip .ST .STX .IMG .ROM .RAW .IPF .CTR .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ atarist %ROM%'
      local -r platform='atarist'
      local -r theme='atarist'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    c64)
      local -r name='c64'
      local -r fullname='Commodore 64'
      local -r path='/home/pi/RetroPie/roms/c64'
      local -r extension='.crt .d64 .g64 .prg .t64 .tap .x64 .zip .vsf .CRT .D64 .G64 .PRG .T64 .TAP .X64 .ZIP .VSF'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ c64 %ROM%'
      local -r platform='c64'
      local -r theme='c64'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    coco)
      local -r name='coco'
      local -r fullname='TRS-80 Color Computer'
      local -r path='/home/pi/RetroPie/roms/coco'
      local -r extension='.cas .wav .bas .asc .dmk .jvc .os9 .dsk .vdk .rom .ccc .sna .CAS .WAV .BAS .ASC .DMK .JVC .OS9 .DSK .VDK .ROM .CCC .SNA'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ coco %ROM%'
      local -r platform='coco'
      local -r theme='coco'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    coleco)
      local -r name='coleco'
      local -r fullname='ColecoVision'
      local -r path='/home/pi/RetroPie/roms/coleco'
      local -r extension='.bin .col .rom .zip .BIN .COL .ROM .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ coleco %ROM%'
      local -r platform='colecovision'
      local -r theme='colecovision'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    dragon32)
      local -r name='dragon32'
      local -r fullname='Dragon 32'
      local -r path='/home/pi/RetroPie/roms/dragon32'
      local -r extension='.cas .wav .bas .asc .dmk .jvc .os9 .dsk .vdk .rom .ccc .sna .CAS .WAV .BAS .ASC .DMK .JVC .OS9 .DSK .VDK .ROM .CCC .SNA'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ dragon32 %ROM%'
      local -r platform='dragon32'
      local -r theme='dragon32'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    dreamcast)
      local -r name='dreamcast'
      local -r fullname='Dreamcast'
      local -r path='/home/pi/RetroPie/roms/dreamcast'
      local -r extension='.cdi .chd .cue .gdi .sh .zip .CDI .CHD .CUE .GDI .SH .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ dreamcast %ROM%'
      local -r platform='dreamcast'
      local -r theme='dreamcast'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    fba)
      local -r name='fba'
      local -r fullname='Final Burn Alpha'
      local -r path='/home/pi/RetroPie/roms/fba'
      local -r extension='.7z .cue .fba .iso .zip .7Z .CUE .FBA .ISO .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ fba %ROM%'
      local -r platform='arcade'
      local -r theme='fba'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    fds)
      local -r name='fds'
      local -r fullname='Famicom Disk System'
      local -r path='/home/pi/RetroPie/roms/fds'
      local -r extension='.7z .nes .fds .zip .7Z .NES .FDS .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ fds %ROM%'
      local -r platform='fds'
      local -r theme='fds'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    gameandwatch)
      local -r name='gameandwatch'
      local -r fullname='Game and Watch'
      local -r path='/home/pi/RetroPie/roms/gameandwatch'
      local -r extension='.mgw .MGW'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ gameandwatch %ROM%'
      local -r platform='gameandwatch'
      local -r theme='gameandwatch'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    gamegear)
      local -r name='gamegear'
      local -r fullname='Sega Gamegear'
      local -r path='/home/pi/RetroPie/roms/gamegear'
      local -r extension='.7z .gg .bin .sms .zip .7Z .GG .BIN .SMS .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ gamegear %ROM%'
      local -r platform='gamegear'
      local -r theme='gamegear'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    gb)
      local -r name='gb'
      local -r fullname='Game Boy'
      local -r path='/home/pi/RetroPie/roms/gb'
      local -r extension='.7z .gb .zip .7Z .GB .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ gb %ROM%'
      local -r platform='gb'
      local -r theme='gb'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    gba)
      local -r name='gba'
      local -r fullname='Game Boy Advance'
      local -r path='/home/pi/RetroPie/roms/gba'
      local -r extension='.7z .gba .zip .7Z .GBA .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ gba %ROM%'
      local -r platform='gba'
      local -r theme='gba'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    gbc)
      local -r name='gbc'
      local -r fullname='Game Boy Color'
      local -r path='/home/pi/RetroPie/roms/gbc'
      local -r extension='.7z .gbc .zip .7Z .GBC .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ gbc %ROM%'
      local -r platform='gbc'
      local -r theme='gbc'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    intellivision)
      local -r name='intellivision'
      local -r fullname='Intellivision'
      local -r path='/home/pi/RetroPie/roms/intellivision'
      local -r extension='.7z .bin .int .itv .rom .zip .7Z .BIN .INT .ITV .ROM .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ intellivision %ROM%'
      local -r platform='intellivision'
      local -r theme='intellivision'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    macintosh)
      local -r name='macintosh'
      local -r fullname='Apple Macintosh'
      local -r path='/home/pi/RetroPie/roms/macintosh'
      local -r extension='.txt .dsk .TXT .DSK'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ macintosh %ROM%'
      local -r platform='macintosh'
      local -r theme='macintosh'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    mame-advmame)
      local -r name='mame-advmame'
      local -r fullname='Multiple Arcade Machine Emulator'
      local -r path='/home/pi/RetroPie/roms/mame-advmame'
      local -r extension='.zip .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ mame-advmame %ROM%'
      local -r platform='arcade'
      local -r theme='mame'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    mame-libretro)
      local -r name='mame-libretro'
      local -r fullname='Multiple Arcade Machine Emulator'
      local -r path='/home/pi/RetroPie/roms/mame-libretro'
      local -r extension='.zip .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ mame-libretro %ROM%'
      local -r platform='arcade'
      local -r theme='mame'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    mame-mame4all)
      local -r name='mame-mame4all'
      local -r fullname='Multiple Arcade Machine Emulator'
      local -r path='/home/pi/RetroPie/roms/mame-mame4all'
      local -r extension='.zip .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ mame-mame4all %ROM%'
      local -r platform='arcade'
      local -r theme='mame'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    mastersystem)
      local -r name='mastersystem'
      local -r fullname='Sega Master System'
      local -r path='/home/pi/RetroPie/roms/mastersystem'
      local -r extension='.7z .sms .bin .zip .7Z .SMS .BIN .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ mastersystem %ROM%'
      local -r platform='mastersystem'
      local -r theme='mastersystem'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    megadrive)
      local -r name='megadrive'
      local -r fullname='Sega Mega Drive'
      local -r path='/home/pi/RetroPie/roms/megadrive'
      local -r extension='.7z .smd .bin .gen .md .sg .zip .7Z .SMD .BIN .GEN .MD .SG .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ megadrive %ROM%'
      local -r platform='megadrive'
      local -r theme='megadrive'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    msx)
      local -r name='msx'
      local -r fullname='MSX'
      local -r path='/home/pi/RetroPie/roms/msx'
      local -r extension='.rom .mx1 .mx2 .col .dsk .zip .m3u .ROM .MX1 .MX2 .COL .DSK .ZIP .M3U'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ msx %ROM%'
      local -r platform='msx'
      local -r theme='msx'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    n64)
      local -r name='n64'
      local -r fullname='Nintendo 64'
      local -r path='/home/pi/RetroPie/roms/n64'
      local -r extension='.z64 .n64 .v64 .zip .Z64 .N64 .V64 .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ n64 %ROM%'
      local -r platform='n64'
      local -r theme='n64'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    neogeo)
      local -r name='neogeo'
      local -r fullname='Neo Geo'
      local -r path='/home/pi/RetroPie/roms/neogeo'
      local -r extension='.7z .chd .cue .fba .iso .zip .7Z .CHD .CUE .FBA .ISO .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ neogeo %ROM%'
      local -r platform='neogeo'
      local -r theme='neogeo'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    nes)
      local -r name='nes'
      local -r fullname='Nintendo Entertainment System'
      local -r path='/home/pi/RetroPie/roms/nes'
      local -r extension='.7z .nes .zip .7Z .NES .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ nes %ROM%'
      local -r platform='nes'
      local -r theme='nes'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    ngp)
      local -r name='ngp'
      local -r fullname='Neo Geo Pocket'
      local -r path='/home/pi/RetroPie/roms/ngp'
      local -r extension='.7z .ngp .zip .7Z .NGP .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ ngp %ROM%'
      local -r platform='ngp'
      local -r theme='ngp'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    ngpc)
      local -r name='ngpc'
      local -r fullname='Neo Geo Pocket Color'
      local -r path='/home/pi/RetroPie/roms/ngpc'
      local -r extension='.7z .ngc .zip .7Z .NGC .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ ngpc %ROM%'
      local -r platform='ngpc'
      local -r theme='ngpc'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    pc)
      local -r name='pc'
      local -r fullname='PC'
      local -r path='/home/pi/RetroPie/roms/pc'
      local -r extension='.bat .com .exe .sh .conf .BAT .COM .EXE .SH .CONF'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ pc %ROM%'
      local -r platform='pc'
      local -r theme='pc'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    pcengine)
      local -r name='pcengine'
      local -r fullname='PC Engine'
      local -r path='/home/pi/RetroPie/roms/pcengine'
      local -r extension='.7z .pce .ccd .chd .cue .zip .7Z .PCE .CCD .CHD .CUE .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ pcengine %ROM%'
      local -r platform='pcengine'
      local -r theme='pcengine'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    ports)
      local -r name='ports'
      local -r fullname='Ports'
      local -r path='/home/pi/RetroPie/roms/ports'
      local -r extension='.sh .SH'
      local -r command='bash %ROM%'
      local -r platform='pc'
      local -r theme='ports'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    psp)
      local -r name='psp'
      local -r fullname='PlayStation Portable'
      local -r path='/home/pi/RetroPie/roms/psp'
      local -r extension='.iso .pbp .cso .ISO .PBP .CSO'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ psp %ROM%'
      local -r platform='psp'
      local -r theme='psp'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    psx)
      local -r name='psx'
      local -r fullname='PlayStation'
      local -r path='/home/pi/RetroPie/roms/psx'
      local -r extension='.cue .cbn .chd .img .iso .m3u .mdf .pbp .toc .z .znx .CUE .CBN .CHD .IMG .ISO .M3U .MDF .PBP .TOC .Z .ZNX'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ psx %ROM%'
      local -r platform='psx'
      local -r theme='psx'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    samcoupe)
      local -r name='samcoupe'
      local -r fullname='SAM Coupe'
      local -r path='/home/pi/RetroPie/roms/samcoupe'
      local -r extension='.dsk .mgt .sbt .sad .DSK .MGT .SBT .SAD'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ samcoupe %ROM%'
      local -r platform='samcoupe'
      local -r theme='samcoupe'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    scummvm)
      local -r name='scummvm'
      local -r fullname='ScummVM'
      local -r path='/home/pi/RetroPie/roms/scummvm'
      local -r extension='.sh .svm .SH .SVM'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ scummvm %ROM%'
      local -r platform='scummvm'
      local -r theme='scummvm'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    sega32x)
      local -r name='sega32x'
      local -r fullname='Sega 32X'
      local -r path='/home/pi/RetroPie/roms/sega32x'
      local -r extension='.7z .32x .smd .bin .md .zip .7Z .32X .SMD .BIN .MD .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ sega32x %ROM%'
      local -r platform='sega32x'
      local -r theme='sega32x'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    segacd)
      local -r name='segacd'
      local -r fullname='Mega CD'
      local -r path='/home/pi/RetroPie/roms/segacd'
      local -r extension='.iso .cue .chd .ISO .CUE .CHD'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ segacd %ROM%'
      local -r platform='segacd'
      local -r theme='segacd'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    sg-1000)
      local -r name='sg-1000'
      local -r fullname='Sega SG-1000'
      local -r path='/home/pi/RetroPie/roms/sg-1000'
      local -r extension='.7z .sg .bin .zip .7Z .SG .BIN .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ sg-1000 %ROM%'
      local -r platform='sg-1000'
      local -r theme='sg-1000'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    snes)
      local -r name='snes'
      local -r fullname='Super Nintendo'
      local -r path='/home/pi/RetroPie/roms/snes'
      local -r extension='.7z .bin .bs .smc .sfc .fig .swc .mgd .zip .7Z .BIN .BS .SMC .SFC .FIG .SWC .MGD .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ snes %ROM%'
      local -r platform='snes'
      local -r theme='snes'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    stratagus)
      local -r name='stratagus'
      local -r fullname='Stratagus Strategy Engine'
      local -r path='/home/pi/RetroPie/roms/stratagus'
      local -r extension='.wc1 .wc2 .sc .data  .WC1 .WC2 .SC .DATA '
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ stratagus %ROM%'
      local -r platform='stratagus'
      local -r theme='stratagus'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    vectrex)
      local -r name='vectrex'
      local -r fullname='Vectrex'
      local -r path='/home/pi/RetroPie/roms/vectrex'
      local -r extension='.7z .vec .gam .bin .zip .7Z .VEC .GAM .BIN .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ vectrex %ROM%'
      local -r platform='vectrex'
      local -r theme='vectrex'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    videopac)
      local -r name='videopac'
      local -r fullname='Videopac'
      local -r path='/home/pi/RetroPie/roms/videopac'
      local -r extension='.7z .bin .zip .7Z .BIN .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ videopac %ROM%'
      local -r platform='videopac'
      local -r theme='videopac'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    virtualboy)
      local -r name='virtualboy'
      local -r fullname='Virtual Boy'
      local -r path='/home/pi/RetroPie/roms/virtualboy'
      local -r extension='.7z .vb .zip .7Z .VB .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ virtualboy %ROM%'
      local -r platform='virtualboy'
      local -r theme='virtualboy'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    wonderswan)
      local -r name='wonderswan'
      local -r fullname='Wonderswan'
      local -r path='/home/pi/RetroPie/roms/wonderswan'
      local -r extension='.7z .ws .zip .7Z .WS .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ wonderswan %ROM%'
      local -r platform='wonderswan'
      local -r theme='wonderswan'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    wonderswancolor)
      local -r name='wonderswancolor'
      local -r fullname='Wonderswan Color'
      local -r path='/home/pi/RetroPie/roms/wonderswancolor'
      local -r extension='.7z .wsc .zip .7Z .WSC .ZIP'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ wonderswancolor %ROM%'
      local -r platform='wonderswancolor'
      local -r theme='wonderswancolor'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    zmachine)
      local -r name='zmachine'
      local -r fullname='Z-machine'
      local -r path='/home/pi/RetroPie/roms/zmachine'
      local -r extension='.dat .zip .z1 .z2 .z3 .z4 .z5 .z6 .z7 .z8 .DAT .ZIP .Z1 .Z2 .Z3 .Z4 .Z5 .Z6 .Z7 .Z8'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ zmachine %ROM%'
      local -r platform='zmachine'
      local -r theme='zmachine'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    zxspectrum)
      local -r name='zxspectrum'
      local -r fullname='ZX Spectrum'
      local -r path='/home/pi/RetroPie/roms/zxspectrum'
      local -r extension='.7z .sh .sna .szx .z80 .tap .tzx .gz .udi .mgt .img .trd .scl .dsk .zip .rzx .7Z .SH .SNA .SZX .Z80 .TAP .TZX .GZ .UDI .MGT .IMG .TRD .SCL .DSK .ZIP .RZX'
      local -r command='/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ zxspectrum %ROM%'
      local -r platform='zxspectrum'
      local -r theme='zxspectrum'
      add_system "${name}" "${fullname}" "${path}" "${extension}" "${command}" "${platform}" "${theme}"
    ;;
    *)
      warn "${system} is an invalid system, please re-enter"
      read system_retry
      create_es_system_list ${system_retry}
    ;;
  esac
}

add_system(){
  ok "Adding ${blue}${1}${clear}"
  echo -e "  <system>\r
      <name>${1}</name>\r
      <fullname>${2}</fullname>\r
      <path>${3}</path>\r
      <extension>${4}</extension>\r
      <command>${5}</command>\r
      <platform>${6}</platform>\r
      <theme>${7}</theme>\r
    </system>" >> /home/${USER}/.emulationstation/es_systems.cfg
}

# Fix permissions of es_systems
setup_custom_file(){
  if [[ -d /home/${USER}/.emulationstation ]]; then
    ok "${blue}/home/${USER}/.emulationstation${white} exists, setting correct permissions"
    sudo chown -R ${USER}:${USER} /home/${USER}/.emulationstation
    if [[ $? -eq 0 ]]; then
      ok "Set owner to ${blue}${USER}${white} for ${blue}/home/${USER}/.emulationstation"
    else
      die "Unable to set owner to ${USER} for /home/${USER}/.emulationstation"
    fi
  else
    ok "${blue}/home/${USER}/.emulationstation${white} does not exist, creating"
    sudo install -d -m 0755 -o ${USER} -g ${USER} /home/${USER}/.emulationstation
    if [[ $? -eq 0 ]]; then
      ok "Created ${blue}/home/${USER}/.emulationstation${white} and set owner to ${blue}${USER}"
    else
      die "Unable to create /home/${USER}/.emulationstation"
    fi
  fi
}

# Create backup of existing es_systems file
make_custom_file_backup(){
  backup_file="/home/${USER}/.emulationstation/es_systems.cfg_backup-$(date +%m-%d-%y_%H-%M)"
  ok "Existing es_systems.cfg found, creating backup ${backup_file}"
  mv /home/${USER}/.emulationstation/es_systems.cfg ${backup_file} && ok "Backup created"
}

choose_options(){
  printf "${blue}Creating custom systems list, please choose an option\n"
  printf "${blue}\t1: Alphabetical list of all installed systems with ROMS\n"
  printf "${blue}\t2: Custom ordered list of all installed systems with ROMS\n"
  printf "${blue}\tq: Abort without making changes\n"
  printf "\n${blue}Please choose an option: ${clear}"
  read answer
  case ${answer} in
    1)
      [[ -f /home/${USER}/.emulationstation/es_systems.cfg ]] && make_custom_file_backup
      echo '<systemList>' > /home/${USER}/.emulationstation/es_systems.cfg
      create_alphabetized_list
      echo '</systemList>' >> /home/${USER}/.emulationstation/es_systems.cfg
    ;;
    2)
      [[ -f /home/${USER}/.emulationstation/es_systems.cfg ]] && make_custom_file_backup
      echo '<systemList>' > /home/${USER}/.emulationstation/es_systems.cfg
      create_custom_list
      echo '</systemList>' >> /home/${USER}/.emulationstation/es_systems.cfg
    ;;
    q)
      printf "No changes have been made"
      printf "To run again please enter ${blue}${0}${clear} and hit return\n"
      sleep 1
      exit 0
    ;;
    *)
      printf "${red}\"${answer}\" is an invalid choice, please try again\n\n"
      choose_options
    ;;
  esac
}

check_rom_directory(){
  if [[ -n "$(ls -A /home/${USER}/RetroPie/roms/${1} 2>/dev/null)" ]];then
    ok "${blue}${1}${white} contains ROMS, adding to list"
    return 0
  else
    return 1
  fi
}

create_alphabetized_list(){
  declare -a es_systems_array
  for system in ags amstradcpc apple2 arcade atari2600 atari5200 atari7800 atari800 atarilynx atarist c64 coco coleco dragon32 dreamcast fba fds gameandwatch gamegear gb gba gbc intellivision macintosh mame-advmame mame-libretro mame-mame4all mastersystem megadrive msx n64 neogeo nes ngp ngpc pc pcengine ports psp psx samcoupe scummvm sega32x segacd sg-1000 snes stratagus vectrex videopac virtualboy wonderswan wonderswancolor zmachine zxspectrum; do
    check_rom_directory ${system}
    [[ $? -eq 0 ]] && es_systems_array+=(${system})
  done
  for list in ${es_systems_array[@]}; do
    create_es_system_list ${list}
  done
}

create_custom_list(){
  declare -a es_systems_array
  for system in ags amstradcpc apple2 arcade atari2600 atari5200 atari7800 atari800 atarilynx atarist c64 coco coleco dragon32 dreamcast fba fds gameandwatch gamegear gb gba gbc intellivision macintosh mame-advmame mame-libretro mame-mame4all mastersystem megadrive msx n64 neogeo nes ngp ngpc pc pcengine ports psp psx samcoupe scummvm sega32x segacd sg-1000 snes stratagus vectrex videopac virtualboy wonderswan wonderswancolor zmachine zxspectrum; do
    check_rom_directory ${system}
    [[ $? -eq 0 ]] && es_list_array+=(${system})
  done
  echo -e "${white}The following systems and ROMs were detected:\n${es_list_array[@]}\n\nEnter systems in order you want them generated, I.E. \"nes gb gbc gba\" and press return${clear}"
  read custom_system_list
  echo -e "${white}Ready to create systems list in the following order\n${blue}${custom_system_list}${white}\nProceed? (y/n)"
  read custom_list_answer
  case ${custom_list_answer} in
    y)
      custom_system_list_array=(${custom_system_list})
      for list in ${custom_system_list[@]}; do
        create_es_system_list ${list}
      done
    ;;
    n)
      ok "Not generating list"
      sleep 1
      exit 0
    ;;
    *)
      die "Invalid option, please choose \"y\" or \"n\""
    ;;
  esac
}

reboot_or_exit(){
  ok "New es_systems.cfg generated.  Do you want to exit script or reboot system?\nChoose 'R' to reboot or any other key to exit"
  read reboot_answer
  case ${reboot_answer} in
    R)
      sudo reboot
    ;;
    *)
      exit 0
    ;;
  esac
}

main(){
  setup_custom_file
  choose_options
  reboot_or_exit
}

main
